#!/usr/bin/env bash

export JAR=gs://hammerlab-lib/coverage-depth-707fccc.jar
export MAIN=org.hammerlab.coverage.Main
if [ -z "$CLUSTER" ]; then
	export CLUSTER="coverage-depth"
fi
"$(dirname "${BASH_SOURCE[0]}")"/../dataproc/dataproc "$@"
